"""image_lagcodec/run_lagcodec.py -- OVERFIT SANITY CHECK, decoder_type="self_attn", optimizer="sinkgd",
recon_ncode maximized to each level's FULL block count (1024,256,64 for strides=(3,4,4)) --
"regress to sequential": a group this large means n_groups=1 per level, so reconstruct_group
decodes the WHOLE sequence as one continuous causal chain with a single growing KV cache and no
group-boundary resets at all -- equivalent to StageSelfAttnDecoder.reconstruct_sequential, just
reached via the existing recon_ncode knob instead of the dedicated method. Confirms whether the
group-boundary "cold start" (each group's first block having zero visibility into any other
group's real/generated bytes) is what was suppressing recon_ncode=2/4/8/16's reconstruction
quality (all four landed at ~1.5-1.8% free-running byte acc despite ~99.6% teacher-forced acc).
Identical training to the other ncode configs (recon_ncode is inference-time only) -- much slower
reconstruction (1024*(K+1) sequential steps, no batch-parallelism across groups), fine for this
100-image / 2000-epoch overfit check.

uv run python3 -m image_lagcodec.run_lagcodec --config image_lagcodec/configs/lagcodec_overfit1000_selfattn_sinkgd_ncode_full.py
"""

run_name = "cifar_lagcodec_overfit1000_selfattn_sinkgd_ncode_full"

# --- model ---
img_size = 32
d_model = (256, 256, 256)
n_layers = (2, 2, 2)
n_heads = (4, 4, 4)
n_kv_heads = (None, None, None)
strides = (3, 4, 4)
code_vocab = 8
pq_chunks = 4
mlp_mult = 4
rope_base = 10000.0
ntp_weight = 1.0
decoder_type = "self_attn"
recon_ncode = (1024, 256, 64)  # = n_units_at(0,1,2) for strides=(3,4,4) -- maximized, one group per level
# dec_d_model/dec_n_layers/dec_n_heads/dec_n_kv_heads left None -> mirror d_model/n_layers/n_heads/n_kv_heads above

# --- training ---
batch_size = 16
n_devices = None
epochs = 2000
lr = 1e-2
warmup_steps = 100
weight_decay = 1e-5
optimizer = "sinkgd"
optimizer_kwargs = {}
seed = 0
train_subset_n = 100

# --- logging / eval ---
log_every = 200
eval_every_epochs = 1000
qual_gen_n = 8
qual_gen_greedy = True
qual_gen_temperature = 1.0
