"""qcute.qcutelm_vlt3 — fork of qcute.qcutelm_vlt2 collapsing the separate
PoolerEncoder/UnpoolerDecoder (two distinct weight sets) into a SINGLE
shared-weight tiny causal transformer that plays both roles, like a normal
byte-level LM with a discrete bottleneck spliced into the middle of its
sequence.

Design (as specified in conversation):
  - "Encoder" stage: feed bytes[0..T-1] through the shared causal blocks,
    with a trainable "code-query" token appended at the end (position T).
    This stage also gets an auxiliary next-token-prediction (NTP) loss on
    the byte positions themselves (standard causal LM loss) — free extra
    gradient signal into the shared weights beyond just the bottleneck
    path, the same role bytelm.py's loss plays, but here shared with the
    tokenizer's own weights instead of a separate model.
  - The code-query position's final hidden state is projected + BSQ-
    quantized -> z_hat (same bsq_quantize as every other module in this
    repo).
  - "Decode" stage: z_hat is projected to a single embedding that becomes
    a *variable* BOS token (content-dependent, not a fixed learned
    vector) — z_proj(z_hat) at position 0, followed by teacher-forced
    byte embeddings chunk[0..T-2] at positions 1..T-1. Run through the
    SAME shared blocks (same weights as the encoder stage) with a causal
    mask, predicting chunk[0..T-1].

Two sequential forward calls through one shared Block stack, not two
separate encoder/decoder module instances — "single model AR, like a tiny
LM" per the design brief. This is mathematically identical to running one
concatenated sequence [bytes, code_query, code_bos, decode_bytes] through
a single attention call with a block mask that (a) lets the code-query
position attend back over the byte region (pooling) and (b) fully blocks
the decode region from attending to the byte/code-query region (so the
bottleneck is enforced structurally, not just by convention) — implemented
here as two plain causal calls instead of one masked call, since the
decode stage's first token (the code embedding) isn't known until the
*entire* encoder stage (all layers) has finished, so the two stages are
inherently sequential regardless of masking; splitting them into two calls
avoids a fragile custom-mask implementation for an equivalent result.

Con (flagged in the design brief, not fixed here): reconstruction decode
is genuinely autoregressive at inference time (unlike qcutelm_vlt2's
one-shot broadcast/prefix decode) — must be generated byte-by-byte, one
step per position. Acceptable because T <= K is small (<=4 in this repo's
configs so far). Training itself is NOT autoregressive-slow: the decode
stage is a single parallel forward pass via teacher forcing (like normal
LM training), so only 2 sequential forward passes are needed per training
step, not T.

No shared imports with qcutelm_vlt/qcutelm_vlt2 (self-contained-module
convention) — Logger/Checkpointer/data-loading/schedule helpers duplicated
verbatim.
"""
from __future__ import annotations

import argparse
import gzip
import json
import math
import time
from dataclasses import asdict, dataclass
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F
from tqdm import tqdm


def format_hms(seconds: float) -> str:
    seconds = int(seconds)
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


class Logger:
    """Same contract as qcute.qcutelm.Logger — see its docstring."""

    def __init__(self, run_dir: Path):
        run_dir.mkdir(parents=True, exist_ok=True)
        self.run_dir = run_dir
        self.text_path = run_dir / "run.log"
        self.json_path = run_dir / "run.jsonl"
        self.text_f = open(self.text_path, "a")
        self.json_f = open(self.json_path, "a")
        self.start_time = time.time()

    def __call__(self, msg: str, **record) -> None:
        elapsed_s = int(time.time() - self.start_time)
        elapsed_hms = format_hms(elapsed_s)
        line = f"[{elapsed_hms}] {msg}"
        tqdm.write(line)
        self.text_f.write(line + "\n")
        self.text_f.flush()
        json_record = {"elapsed_s": elapsed_s, "elapsed_hms": elapsed_hms, **({} if record else {"msg": msg}), **record}
        self.json_f.write(json.dumps(json_record) + "\n")
        self.json_f.flush()


class Checkpointer:
    """Same contract as qcute.qcutelm.Checkpointer — see its docstring."""

    def __init__(self, run_dir: Path, save_every_n_evals: int = 1, minimize: bool = True):
        run_dir.mkdir(parents=True, exist_ok=True)
        self.best_path = run_dir / "best.pt"
        self.last_path = run_dir / "last.pt"
        self.save_every_n_evals = max(1, save_every_n_evals)
        self.minimize = minimize
        self.best_metric = float("inf") if minimize else float("-inf")
        self._eval_count = 0

    def is_better(self, metric: float) -> bool:
        return metric < self.best_metric if self.minimize else metric > self.best_metric

    def step(self, state: dict, metric: float) -> None:
        self._eval_count += 1
        if self.is_better(metric):
            self.best_metric = metric
            torch.save(state, self.best_path)
        if self._eval_count % self.save_every_n_evals == 0:
            torch.save(state, self.last_path)


@dataclass
class Config:
    K: int = 4                  # max chunk length (curriculum trains 1..K)
    dq: int = 18                # code dims (BSQ: 1 bit/dim; FSQ: log2(fsq_levels) bits/dim)
    lfq: bool = False
    quant_type: str = "bsq"     # "bsq", "fsq", or "ifsq" (fsq w/ sigmoid bound)
    fsq_levels: int = 8         # FSQ: number of quantization levels per dimension
    vocab: int = 256
    d_model: int = 128          # single shared-weight width (no separate enc/dec widths)
    n_heads: int = 4
    n_layers: int = 2           # single shared block stack depth
    mlp_mult: int = 4
    ntp_loss_weight: float = 0.5  # weight on the encoder-region auxiliary NTP loss


def build_config(dq: int | None, **kwargs) -> Config:
    if dq is None:
        dq = 18
    return Config(dq=dq, **kwargs)


def bsq_quantize(v: torch.Tensor, dq: int, lfq: bool = False) -> tuple[torch.Tensor, torch.Tensor]:
    """Identical math to qcute.qcutelm.bsq_quantize — duplicated per this
    repo's self-contained-module convention, not an oversight."""
    if lfq:
        z_hat = v + (torch.sign(v) - v).detach()
        targets = (v > 0).float().detach()
        return z_hat, targets
    v_unit = F.normalize(v, dim=-1)
    z_hat = (v_unit + (torch.sign(v_unit) - v_unit).detach()) / math.sqrt(dq)
    targets = (v_unit > 0).float().detach()
    return z_hat, targets


def fsq_quantize(v: torch.Tensor, levels: int, bound: str = "tanh") -> torch.Tensor:
    """Finite Scalar Quantization (Mentzer et al. 2023) — each of the dq
    dimensions is quantized independently to one of `levels` values, unlike
    BSQ's single global L2-normalize + per-dim sign (effectively 2 levels).
    No shared-across-dims normalize step: bound each dim to (-1, 1), scale
    to the level grid, round with a straight-through estimator, rescale
    back to (-1, 1). No `targets`/no explicit L2-normalize Jacobian to
    contract gradients the way BSQ's does — see this module's
    training-dynamics discussion for why this matters.

    bound="sigmoid" is the "iFSQ" variant (user-supplied): replaces tanh's
    bounding with 2*sigmoid(1.6*z)-1, intended to spread the pre-rounding
    distribution more uniformly across (-1, 1) than tanh's is bunched
    toward the extremes, which should mean the STE rounding step's error
    is more evenly distributed across bins instead of concentrated near
    the center where tanh is closest to linear."""
    half_l = (levels - 1) / 2
    z = torch.tanh(v) if bound == "tanh" else (2 * torch.sigmoid(1.6 * v) - 1)
    bounded = z * half_l  # (-half_l, half_l)
    z_hat = bounded + (torch.round(bounded) - bounded).detach()  # STE round to nearest level
    return z_hat / half_l  # back to (-1, 1)


class ZeroKVCausalSelfAttention(nn.Module):
    """Causal self-attention with a single zero key/value pair concatenated
    before SDPA (Miller 2023, "Attention Is Off By One") — escape-hatch
    role, as in qcutelm_vlt2. Always causal over whatever local sequence is
    passed in; the encoder-stage and decode-stage sequences are built and
    passed in separately by SharedARTokenizer, so this needs no awareness
    of the two-region structure itself."""

    def __init__(self, d_model: int, n_heads: int):
        super().__init__()
        self.n_heads = n_heads
        self.head_dim = d_model // n_heads
        self.qkv = nn.Linear(d_model, 3 * d_model, bias=False)
        self.out = nn.Linear(d_model, d_model, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, T, D = x.shape
        H, hd = self.n_heads, self.head_dim
        qkv = self.qkv(x).reshape(B, T, 3, H, hd).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]  # [B, H, T, hd]
        zero_kv = torch.zeros(B, H, 1, hd, device=x.device, dtype=x.dtype)
        k = torch.cat([zero_kv, k], dim=2)  # [B, H, 1+T, hd]
        v = torch.cat([zero_kv, v], dim=2)
        attn_mask = torch.zeros(T, 1 + T, dtype=torch.bool, device=x.device)
        attn_mask[:, 0] = True  # sink slot always visible to every query
        attn_mask[:, 1:] = torch.tril(torch.ones(T, T, dtype=torch.bool, device=x.device))
        y = F.scaled_dot_product_attention(q, k, v, attn_mask=attn_mask)
        return self.out(y.transpose(1, 2).reshape(B, T, D))


class Block(nn.Module):
    """Pre-norm residual: zero-KV causal self-attention + MLP. This single
    stack is reused for BOTH the encoder stage and the decode stage —
    that's the whole point of this fork (shared weights, not two towers)."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.ln1 = nn.LayerNorm(cfg.d_model)
        self.attn = ZeroKVCausalSelfAttention(cfg.d_model, cfg.n_heads)
        self.ln2 = nn.LayerNorm(cfg.d_model)
        self.mlp = nn.Sequential(
            nn.Linear(cfg.d_model, cfg.mlp_mult * cfg.d_model), nn.SiLU(),
            nn.Linear(cfg.mlp_mult * cfg.d_model, cfg.d_model),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x + self.attn(self.ln1(x))
        x = x + self.mlp(self.ln2(x))
        return x


class SharedARTokenizer(nn.Module):
    """Single shared-weight tiny causal LM playing both encoder and
    decoder roles. See module docstring for the two-stage design."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.cfg = cfg
        self.byte_emb = nn.Embedding(cfg.vocab, cfg.d_model)  # NoPE — shared by both stages
        self.code_query_emb = nn.Parameter(torch.zeros(cfg.d_model))
        nn.init.normal_(self.code_query_emb, std=0.02)
        self.blocks = nn.ModuleList([Block(cfg) for _ in range(cfg.n_layers)])
        self.ln_f = nn.LayerNorm(cfg.d_model)
        self.head = nn.Linear(cfg.d_model, cfg.vocab)  # shared vocab head, both stages
        self.code_proj = nn.Linear(cfg.d_model, cfg.dq)   # code-query hidden -> code
        self.z_proj = nn.Linear(cfg.dq, cfg.d_model)      # code -> decode-stage BOS embedding

    def run_blocks(self, x: torch.Tensor) -> torch.Tensor:
        for block in self.blocks:
            x = block(x)
        return self.ln_f(x)

    def quantize(self, raw: torch.Tensor) -> torch.Tensor:
        """Dispatch to BSQ/FSQ/iFSQ per cfg.quant_type — the only place
        that needs to know which scheme is in use."""
        if self.cfg.quant_type == "fsq":
            return fsq_quantize(raw, self.cfg.fsq_levels, bound="tanh")
        if self.cfg.quant_type == "ifsq":
            return fsq_quantize(raw, self.cfg.fsq_levels, bound="sigmoid")
        z_hat, _ = bsq_quantize(raw, self.cfg.dq, self.cfg.lfq)
        return z_hat

    def encode(self, chunk: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        # chunk: [B, T] long -> (z_hat: [B, dq], ntp_logits: [B, T-1, vocab] or None, enc_h: [B, T+1, d_model])
        B, T = chunk.shape
        byte_x = self.byte_emb(chunk)  # [B, T, D]
        query_x = self.code_query_emb.view(1, 1, -1).expand(B, 1, -1)
        enc_in = torch.cat([byte_x, query_x], dim=1)  # [B, T+1, D]
        enc_h = self.run_blocks(enc_in)
        ntp_logits = self.head(enc_h[:, :T - 1, :]) if T > 1 else None  # predict chunk[1..T-1]
        z_hat = self.quantize(self.code_proj(enc_h[:, T, :]))
        return z_hat, ntp_logits, enc_h

    def encode_joint(self, chunk: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """Joint-training variant of encode(): the NTP prediction head is
        conditioned on the code the encoder itself just produced (code_emb
        added into the pre-head hidden states), instead of the plain
        forward()'s code-blind NTP. This ties the auxiliary NTP loss's
        gradient directly to code quality — the code must help explain the
        chunk's own local byte-to-byte structure, not just the full
        reconstruction it already has to support via decode() — a second,
        more direct regularizer on what the code encodes."""
        B, T = chunk.shape
        byte_x = self.byte_emb(chunk)
        query_x = self.code_query_emb.view(1, 1, -1).expand(B, 1, -1)
        enc_in = torch.cat([byte_x, query_x], dim=1)
        enc_h = self.run_blocks(enc_in)
        z_hat = self.quantize(self.code_proj(enc_h[:, T, :]))
        code_emb = self.z_proj(z_hat)  # [B, D] — same projection decode() uses for its BOS
        if T > 1:
            ntp_logits = self.head(enc_h[:, :T - 1, :] + code_emb.unsqueeze(1))
        else:
            ntp_logits = None
        return z_hat, ntp_logits

    def forward_joint(self, chunk: torch.Tensor) -> tuple[torch.Tensor, dict]:
        """Joint-training objective: fixed T (no curriculum), simplified to
        two accuracies — recon_acc (the real tokenizer objective: decode
        reconstruction) and aux_recon_acc (the code-conditioned NTP
        prediction, itself a byte-reconstruction task — 'auxiliary
        reconstruction' rather than a free-standing LM loss)."""
        z_hat, ntp_logits = self.encode_joint(chunk)
        dec_logits = self.decode(z_hat, chunk)

        recon_loss = F.cross_entropy(dec_logits.reshape(-1, self.cfg.vocab), chunk.reshape(-1))
        recon_acc = (dec_logits.argmax(-1) == chunk).float().mean()

        if ntp_logits is not None:
            ntp_targets = chunk[:, 1:]
            aux_recon_loss = F.cross_entropy(ntp_logits.reshape(-1, self.cfg.vocab), ntp_targets.reshape(-1))
            aux_recon_acc = (ntp_logits.argmax(-1) == ntp_targets).float().mean()
        else:
            aux_recon_loss = torch.zeros((), device=chunk.device)
            aux_recon_acc = torch.ones((), device=chunk.device)

        loss = recon_loss + self.cfg.ntp_loss_weight * aux_recon_loss
        return loss, {
            "loss": loss, "recon_loss": recon_loss, "aux_recon_loss": aux_recon_loss,
            "recon_acc": recon_acc, "aux_recon_acc": aux_recon_acc,
        }

    def decode(self, z_hat: torch.Tensor, chunk: torch.Tensor) -> torch.Tensor:
        # z_hat: [B, dq], chunk: [B, T] (teacher-forcing targets) -> logits: [B, T, vocab]
        B, T = chunk.shape
        bos = self.z_proj(z_hat).unsqueeze(1)  # [B, 1, D] — variable, content-dependent BOS
        if T > 1:
            dec_in = torch.cat([bos, self.byte_emb(chunk[:, :-1])], dim=1)  # [B, T, D]
        else:
            dec_in = bos
        dec_h = self.run_blocks(dec_in)
        return self.head(dec_h)

    @torch.no_grad()
    def decode_greedy(self, z_hat: torch.Tensor, T: int) -> torch.Tensor:
        """Actual autoregressive generation (the 'con': one step per byte).
        Not used in training (teacher forcing there); provided for
        qualitative inspection / inference-time use."""
        B = z_hat.size(0)
        bos = self.z_proj(z_hat).unsqueeze(1)  # [B, 1, D]
        seq = bos
        out_bytes = []
        for _ in range(T):
            h = self.run_blocks(seq)
            logits = self.head(h[:, -1, :])  # [B, vocab]
            next_byte = logits.argmax(-1)
            out_bytes.append(next_byte)
            seq = torch.cat([seq, self.byte_emb(next_byte).unsqueeze(1)], dim=1)
        return torch.stack(out_bytes, dim=1)  # [B, T]

    def forward(self, chunk: torch.Tensor) -> tuple[torch.Tensor, dict]:
        B, T = chunk.shape
        z_hat, ntp_logits, _ = self.encode(chunk)
        dec_logits = self.decode(z_hat, chunk)

        recon_loss = F.cross_entropy(dec_logits.reshape(-1, self.cfg.vocab), chunk.reshape(-1))
        correct = dec_logits.argmax(-1) == chunk
        acc = correct.float().mean()
        first_byte_acc = correct[:, 0].float().mean()

        if ntp_logits is not None:
            ntp_targets = chunk[:, 1:]
            ntp_loss = F.cross_entropy(ntp_logits.reshape(-1, self.cfg.vocab), ntp_targets.reshape(-1))
        else:
            ntp_loss = torch.zeros((), device=chunk.device)

        loss = recon_loss + self.cfg.ntp_loss_weight * ntp_loss
        return loss, {
            "loss": loss, "recon_loss": recon_loss, "ntp_loss": ntp_loss,
            "recon_acc": acc, "first_byte_acc": first_byte_acc,
        }


def init_head_bias_to_unigram(model: SharedARTokenizer, data: torch.Tensor) -> None:
    """Same GPT-2-style bias-init trick as elsewhere in this repo — free
    head start on the shared vocab head, no architecture change."""
    counts = torch.bincount(data, minlength=256).float() + 1.0
    log_freq = torch.log(counts / counts.sum())
    with torch.no_grad():
        model.head.bias.copy_(log_freq.to(model.head.bias.device))


def load_enwik8(path: Path, n_bytes: int | None = None) -> torch.Tensor:
    with gzip.open(path, "rb") as f:
        data = f.read(n_bytes) if n_bytes else f.read()
    return torch.tensor(list(data), dtype=torch.long)


def split_train_val(data: torch.Tensor, val_frac: float) -> tuple[torch.Tensor, torch.Tensor]:
    n_val = max(1, int(len(data) * val_frac))
    return data[:-n_val], data[-n_val:]


def sample_chunks(data: torch.Tensor, batch_size: int, T: int, device: str) -> torch.Tensor:
    n = max(1, len(data) - T)
    starts = torch.randint(0, n, (batch_size,))
    return torch.stack([data[s:s + T] for s in starts]).to(device)


def lr_at(step: int, warmup: int, peak: float) -> float:
    if step < warmup:
        return peak * step / max(1, warmup)
    return peak


def lr_at_warmup_constant_cosine(
    step: int, warmup: int, constant_steps: int, peak: float, total_steps: int, min_lr_frac: float = 0.1,
) -> float:
    if step < warmup:
        return peak * step / max(1, warmup)
    decay_start = warmup + constant_steps
    if step < decay_start:
        return peak
    min_lr = peak * min_lr_frac
    progress = min(1.0, (step - decay_start) / max(1, total_steps - decay_start))
    return min_lr + 0.5 * (peak - min_lr) * (1 + math.cos(math.pi * progress))


def load_config_module(path: Path) -> dict:
    import importlib.util

    spec = importlib.util.spec_from_file_location(path.stem, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return {k: v for k, v in vars(module).items() if not k.startswith("_")}


@torch.no_grad()
def eval_recon_acc(model: SharedARTokenizer, data: torch.Tensor, T: int, batch_size: int, n_batches: int, device: str) -> tuple[float, float]:
    model.eval()
    correct = total = 0
    first_correct = first_total = 0
    for _ in range(n_batches):
        batch = sample_chunks(data, batch_size, T, device)
        z_hat, _, _ = model.encode(batch)
        logits = model.decode(z_hat, batch)
        match = logits.argmax(-1) == batch
        correct += match.float().sum().item()
        total += batch.numel()
        first_correct += match[:, 0].float().sum().item()
        first_total += match.size(0)
    model.train()
    return correct / total, first_correct / first_total


@torch.no_grad()
def eval_joint(model: SharedARTokenizer, data: torch.Tensor, T: int, batch_size: int, n_batches: int, device: str) -> tuple[float, float]:
    """Val-set version of forward_joint()'s two accuracies: (recon_acc, aux_recon_acc)."""
    model.eval()
    correct = total = 0
    aux_correct = aux_total = 0
    for _ in range(n_batches):
        batch = sample_chunks(data, batch_size, T, device)
        z_hat, ntp_logits = model.encode_joint(batch)
        logits = model.decode(z_hat, batch)
        match = logits.argmax(-1) == batch
        correct += match.float().sum().item()
        total += batch.numel()
        if ntp_logits is not None:
            ntp_targets = batch[:, 1:]
            aux_match = ntp_logits.argmax(-1) == ntp_targets
            aux_correct += aux_match.float().sum().item()
            aux_total += aux_match.numel()
    model.train()
    return correct / total, (aux_correct / aux_total if aux_total > 0 else 1.0)


def train_joint(model: SharedARTokenizer, train_data: torch.Tensor, val_data: torch.Tensor, args, log, run_name: str, device: str) -> None:
    """Joint training: everything random init, fixed T=cfg.K throughout (no
    curriculum staging, no replay, no forgetting-check — there are no
    earlier stages to have forgotten), simplified to the two accuracies
    forward_joint() tracks. Uses encode_joint(), which conditions the
    auxiliary NTP loss on the code the encoder just produced, instead of
    plain forward()'s code-blind NTP."""
    cfg = model.cfg
    init_head_bias_to_unigram(model, train_data)
    opt = torch.optim.AdamW(model.parameters(), lr=args.lr_peak, betas=(0.9, 0.95), weight_decay=args.weight_decay)
    checkpointer = Checkpointer(args.checkpoint_dir / run_name, args.save_every_n_evals, minimize=True)

    T = cfg.K
    model.train()
    pbar = tqdm(range(1, args.steps + 1), desc="train_vlt3_joint", dynamic_ncols=True)
    for step in pbar:
        if args.cosine_decay:
            lr = lr_at_warmup_constant_cosine(step, args.warmup_steps, args.constant_steps, args.lr_peak, args.steps)
        else:
            lr = lr_at(step, args.warmup_steps, args.lr_peak)
        for g in opt.param_groups:
            g["lr"] = lr

        batch = sample_chunks(train_data, args.batch_size, T, device)
        loss, metrics = model.forward_joint(batch)
        opt.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
        opt.step()

        acc = metrics["recon_acc"].item()
        aux_acc = metrics["aux_recon_acc"].item()
        pbar.set_postfix(lr=f"{lr:.2e}", loss=f"{loss.item():.4f}", recon_loss=f"{metrics['recon_loss'].item():.4f}",
                          aux_recon_loss=f"{metrics['aux_recon_loss'].item():.4f}",
                          recon_acc=f"{acc*100:.2f}%", aux_recon_acc=f"{aux_acc*100:.2f}%")

        if step % args.eval_every == 0 or step == args.steps:
            val_acc, val_aux_acc = eval_joint(model, val_data, T, args.batch_size, args.eval_batches, device)
            log(f"{pbar}  val_recon_acc={val_acc*100:.2f}%  val_aux_recon_acc={val_aux_acc*100:.2f}%",
                step=step, train_recon_acc=acc, aux_recon_acc=aux_acc, val_recon_acc=val_acc, val_aux_recon_acc=val_aux_acc)
            checkpointer.step({"model": model.state_dict(), "cfg": asdict(cfg), "step": step, "val_recon_acc": val_acc}, 1.0 - val_acc)
            if acc >= args.curriculum_target_acc:
                log(f"target reached: train_recon_acc {acc*100:.2f}% >= {args.curriculum_target_acc*100:.1f}% at step {step}", step=step)
                return


def train_curriculum(model: SharedARTokenizer, train_data: torch.Tensor, val_data: torch.Tensor, args, log, run_name: str, device: str) -> None:
    """Same curriculum/replay/forgetting-check/point-estimate-gating logic
    as qcute.qcutelm_vlt2.train_curriculum — see that module's docstring."""
    cfg = model.cfg
    init_head_bias_to_unigram(model, train_data)
    opt = torch.optim.AdamW(model.parameters(), lr=args.lr_peak, betas=(0.9, 0.95), weight_decay=args.weight_decay)
    checkpointer = Checkpointer(args.checkpoint_dir / run_name, args.save_every_n_evals, minimize=True)

    T = cfg.K if args.no_curriculum else 1
    stage_step = 0
    model.train()
    pbar = tqdm(range(1, args.steps + 1), desc="train_vlt3", dynamic_ncols=True)
    for step in pbar:
        if args.cosine_decay:
            lr = lr_at_warmup_constant_cosine(step, args.warmup_steps, args.constant_steps, args.lr_peak, args.steps)
        else:
            lr = lr_at(step, args.warmup_steps, args.lr_peak)
        for g in opt.param_groups:
            g["lr"] = lr

        is_eval_step = step % args.eval_every == 0 or step == args.steps
        T_step = T
        if not args.no_curriculum and not is_eval_step and T > 1 and args.replay_frac > 0 and torch.rand(()).item() < args.replay_frac:
            T_step = int(torch.randint(1, T + 1, (1,)).item())
        batch = sample_chunks(train_data, args.batch_size, T_step, device)
        loss, metrics = model(batch)
        opt.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
        opt.step()

        acc = metrics["recon_acc"].item()
        first_acc = metrics["first_byte_acc"].item()
        pbar.set_postfix(lr=f"{lr:.2e}", T=T, T_step=T_step, loss=f"{loss.item():.4f}",
                          recon_loss=f"{metrics['recon_loss'].item():.4f}", ntp_loss=f"{metrics['ntp_loss'].item():.4f}",
                          train_recon_acc=f"{acc*100:.2f}%", first_byte_acc=f"{first_acc*100:.2f}%")
        stage_step += 1

        if is_eval_step:
            val_acc, val_first_acc = eval_recon_acc(model, val_data, T, args.batch_size, args.eval_batches, device)
            prior_accs = {} if args.no_curriculum else {
                t: eval_recon_acc(model, val_data, t, args.batch_size, args.eval_batches, device)[0]
                for t in range(1, T)
            }
            prior_str = "  ".join(f"T{t}_acc={a*100:.2f}%" for t, a in prior_accs.items())
            log(f"{pbar}  T={T}  val_acc={val_acc*100:.2f}%  val_first_byte_acc={val_first_acc*100:.2f}%" + (f"  {prior_str}" if prior_str else ""),
                step=step, T=T, train_recon_acc=acc, first_byte_acc=first_acc, val_recon_acc=val_acc,
                val_first_byte_acc=val_first_acc, **{f"T{t}_val_acc": a for t, a in prior_accs.items()})
            checkpointer.step({"model": model.state_dict(), "cfg": asdict(cfg), "step": step, "T": T, "val_recon_acc": val_acc}, 1.0 - val_acc)
            if not args.no_curriculum and T < cfg.K and (
                acc >= args.curriculum_target_acc or stage_step >= args.curriculum_max_steps_per_stage
            ):
                reason = "target_acc" if acc >= args.curriculum_target_acc else "max_steps_per_stage"
                T += 1
                stage_step = 0
                log(f"curriculum advance ({reason}): T={T}", step=step, T=T)
            elif T == cfg.K and acc >= args.curriculum_target_acc:
                log(f"target reached at final stage T={T}: train_recon_acc {acc*100:.2f}% >= "
                    f"{args.curriculum_target_acc*100:.1f}% at step {step}", step=step, T=T)
                return


def main():
    pre = argparse.ArgumentParser(add_help=False)
    pre.add_argument("--config", type=Path, default=None)
    pre_args, _ = pre.parse_known_args()

    p = argparse.ArgumentParser(description="Single shared-weight AR tokenizer (fork of qcute.qcutelm_vlt2)", parents=[pre])
    p.add_argument("--K", type=int, default=4)
    p.add_argument("--dq", type=int, default=None)
    p.add_argument("--lfq", action="store_true")
    p.add_argument("--quant_type", type=str, default="bsq", choices=["bsq", "fsq", "ifsq"])
    p.add_argument("--fsq_levels", type=int, default=8)
    p.add_argument("--d_model", type=int, default=128)
    p.add_argument("--n_heads", type=int, default=4)
    p.add_argument("--n_layers", type=int, default=2)
    p.add_argument("--mlp_mult", type=int, default=4)
    p.add_argument("--ntp_loss_weight", type=float, default=0.5)

    p.add_argument("--data", type=Path, default=Path("datasets/enwik8_1M.gz"))
    p.add_argument("--n_bytes", type=int, default=None)
    p.add_argument("--val_frac", type=float, default=0.1)

    p.add_argument("--steps", type=int, default=20000)
    p.add_argument("--batch_size", type=int, default=16)
    p.add_argument("--lr_peak", type=float, default=3e-4)
    p.add_argument("--weight_decay", type=float, default=1e-5)
    p.add_argument("--warmup_steps", type=int, default=500)
    p.add_argument("--cosine_decay", action="store_true")
    p.add_argument("--constant_steps", type=int, default=100)
    p.add_argument("--grad_clip", type=float, default=1.0)
    p.add_argument("--eval_every", type=int, default=100)
    p.add_argument("--eval_batches", type=int, default=20)

    p.add_argument("--joint", action="store_true", help="train_joint: random init, fixed T=K, no curriculum/replay")
    p.add_argument("--no_curriculum", action="store_true")
    p.add_argument("--replay_frac", type=float, default=0.2)
    p.add_argument("--curriculum_target_acc", type=float, default=0.95)
    p.add_argument("--curriculum_max_steps_per_stage", type=int, default=2000)

    p.add_argument("--run_name", type=str, default=None)
    p.add_argument("--logs_dir", type=Path, default=Path("logs"))
    p.add_argument("--checkpoint_dir", type=Path, default=Path("checkpoints"))
    p.add_argument("--save_every_n_evals", type=int, default=1)

    if pre_args.config:
        p.set_defaults(**{k: v for k, v in load_config_module(pre_args.config).items() if k in {a.dest for a in p._actions}})
    args = p.parse_args()

    device = "mps" if torch.backends.mps.is_available() else ("cuda" if torch.cuda.is_available() else "cpu")
    cfg = build_config(
        args.dq, K=args.K, lfq=args.lfq, quant_type=args.quant_type, fsq_levels=args.fsq_levels,
        d_model=args.d_model, n_heads=args.n_heads,
        n_layers=args.n_layers, mlp_mult=args.mlp_mult, ntp_loss_weight=args.ntp_loss_weight,
    )
    model = SharedARTokenizer(cfg).to(device)
    n_params = sum(p_.numel() for p_ in model.parameters())

    run_name = args.run_name or (pre_args.config.stem if pre_args.config else f"qcutelm_vlt3_{int(time.time())}")
    log = Logger(args.logs_dir / run_name)
    print(f"run_name={run_name}  logging to {log.text_path} — tail -f {log.text_path}")
    log(f"K={cfg.K} dq={cfg.dq} params={n_params/1e6:.3f}M (single shared stack) device={device}")

    data = load_enwik8(args.data, args.n_bytes)
    train_data, val_data = split_train_val(data, args.val_frac)
    log(f"train_bytes={len(train_data)}  val_bytes={len(val_data)}")

    if args.joint:
        train_joint(model, train_data, val_data, args, log, run_name, device)
    else:
        train_curriculum(model, train_data, val_data, args, log, run_name, device)


if __name__ == "__main__":
    main()
