"""Inference + consistency checks for image_gen/summformer.py, on a random-init model (no
checkpoint needed) with a random 64x64x3 RGB tensor as the prompt -- per the "first job" scope:
training + inference + consistency check, nothing beyond that yet (no real parallel-decode
generation loop -- see summformer.py's module docstring for why that's explicitly out of scope
here).

Three checks:
  1. generate_no_cache produces a valid byte sequence (0-255) of the requested length.
  2. Two calls with the same key produce the SAME output (determinism), two different keys
     produce DIFFERENT output (sampling actually varies) -- basic sanity, not architecture-specific.
  3. check_block_locality: probes whether a distant byte affects a given position's logits,
     reported alongside whether that position is inside the byte's main_window or reachable via a
     fuse-stage, so you can visually confirm the block-local-plus-reconnection structure matches
     what the config claims.

Also saves the generated bytes reshaped to (resolution, resolution, 3) as a real PNG.

    uv run python summformer_jax/image_gen/inference.py --config summformer_jax/image_gen/configs/image64_test.py
"""
from __future__ import annotations

import argparse
from dataclasses import fields
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
from flax import nnx
from PIL import Image

from summformer import ConfigV2, SummTransformerV2, check_block_locality
from train import load_config_module, build_config


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--config", type=Path, required=True)
    p.add_argument("--resolution", type=int, default=64)
    p.add_argument("--prompt-len", type=int, default=192, help="bytes of random prompt before generation starts")
    p.add_argument("--gen-tokens", type=int, default=None, help="default: fill out the rest of the image")
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--out", type=str, default="summformer_jax/image_gen/sample.png")
    args = p.parse_args()

    config_vars = load_config_module(args.config)
    cfg = build_config(config_vars)
    seq_len = args.resolution * args.resolution * 3
    assert seq_len == cfg.context_len, f"resolution^2*3={seq_len} != cfg.context_len={cfg.context_len}"
    gen_tokens = args.gen_tokens if args.gen_tokens is not None else seq_len - args.prompt_len

    model = SummTransformerV2(cfg, rngs=nnx.Rngs(args.seed))

    key = jax.random.PRNGKey(args.seed)
    prompt = jax.random.randint(key, (args.prompt_len,), 0, cfg.vocab_size)

    # --- check 1: valid byte sequence ---
    out = model.generate_no_cache(prompt, gen_tokens, key=None)  # greedy
    assert out.shape[0] == args.prompt_len + gen_tokens
    assert bool(jnp.all((out >= 0) & (out < cfg.vocab_size)))
    print(f"[PASS] generate_no_cache produced {out.shape[0]} valid bytes (greedy)")

    # --- check 2: determinism + sampling variation ---
    out_a = model.generate_no_cache(prompt, 16, key=jax.random.PRNGKey(42), temperature=1.0)
    out_b = model.generate_no_cache(prompt, 16, key=jax.random.PRNGKey(42), temperature=1.0)
    out_c = model.generate_no_cache(prompt, 16, key=jax.random.PRNGKey(43), temperature=1.0)
    same_key_match = bool(jnp.array_equal(out_a, out_b))
    diff_key_differs = not bool(jnp.array_equal(out_a, out_c))
    print(f"[{'PASS' if same_key_match else 'FAIL'}] same key -> identical output")
    print(f"[{'PASS' if diff_key_differs else 'FAIL'}] different key -> different output")

    # --- check 3: block-locality probe ---
    print("\nblock-locality probe (query_pos, probe_pos, affected, max_abs_diff):")
    window = cfg.main_window if isinstance(cfg.main_window, int) else None
    probes = [
        ("probe just inside window", seq_len // 2, seq_len // 2 - (window - 1 if window else 1)),
        ("probe just outside window, no fuse-stage reach", seq_len // 2, max(0, seq_len // 2 - (window + 5 if window else seq_len))),
        ("probe far away (start of sequence)", seq_len - 1, 0),
    ]
    for label, q, pr in probes:
        if q >= seq_len or pr >= q:
            continue
        result = check_block_locality(model, nnx.Rngs(args.seed), seq_len, q, pr)
        print(f"  {label}: q={q} probe={pr} affected={result['affected']} max_abs_diff={result['max_abs_diff']:.6f}")

    # --- save PNG ---
    if seq_len == args.resolution * args.resolution * 3:
        img_bytes = np.array(out[:seq_len])
        img = img_bytes.reshape(args.resolution, args.resolution, 3).astype(np.uint8)
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Image.fromarray(img).save(args.out)
        print(f"\nsaved generated image to {args.out}")


if __name__ == "__main__":
    main()
