"""Diagnostic: real sequential byte generation for a StackDecoder n_levels==3 checkpoint, but with
EVERY decode cross-attention code (track1 AND track2) forced to the real/ground-truth code
(freshly computed by encoders[1]/encoders[2] from the true byte stream, never the model's own
forecast) -- isolating whether decode itself (given oracle-quality upper codes) can reconstruct
the true byte string via genuine incremental generation, independent of upper-level forecast
quality. Self-attention context (the growing byte buffer) still comes from the model's OWN
just-generated bytes, matching real generation's actual compounding risk -- only the
cross-attended codes are cheated to ground truth.

Hardcoded against the ks221_v256_pq1_overfit10k_window16_relaxed checkpoint (CKPT/DATA below) --
edit those two constants to point at a different run. Run from repo root:

    uv run python scripts/probe_gt_code_generation.py
"""
import gzip
import sys
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from qcute.qcute_v1.qcute_v1_common import Config
from qcute.qcute_v1.qcute_v1_decoder import (
    encode_like_self_attn_decode, seed_query_decode, upper_track_step, sample_next_byte,
)
from qcute.qcute_v1.qcute_v1 import QCuteLM

CKPT = "logs/v1_stack_simplex_ks221_v256_pq1_overfit10k_window16_relaxed/last.pt"
DATA = "datasets/enwik8_1M.gz"

device = "cpu"
ckpt = torch.load(CKPT, map_location=device)
cfg = Config(**ckpt["cfg"])
model = QCuteLM(cfg).to(device)
model.load_state_dict(ckpt["model"])
model.eval()
decoder = model.decoder

with gzip.open(DATA, "rb") as f:
    raw = f.read()
n_bytes = 10000
data = torch.tensor(list(raw[:n_bytes]), dtype=torch.long)

K0, K1, K2 = cfg.Ks
cum_K1 = K0 * K1
cum_K2 = K0 * K1 * K2
bb0, bb1, bb2 = decoder.stage_lms[0][0], decoder.stage_lms[0][1], decoder.stage_lms[0][2]
D = bb0.d_model
track0_window = model.decode_windows[0][0]

SEQ_LEN = 256
PROMPT_LEN = 32


def run(start):
    full_bytes = data[start:start + SEQ_LEN].unsqueeze(0)
    with torch.no_grad():
        all_bytes = full_bytes[:, :PROMPT_LEN // K0 * K0]
        n_blocks_prompt = all_bytes.shape[1] // K0
        code_parts = []
        if n_blocks_prompt > 0:
            code_parts = [model.encoders[0](all_bytes, level=0, window=model.windows[0],
                                             compute_ntp=False)["code"][:, :n_blocks_prompt, :]]

        n_total_blocks = full_bytes.shape[1] // K0
        n_new_blocks = n_total_blocks - n_blocks_prompt

        for _ in range(n_new_blocks):
            n_blocks_prev = all_bytes.shape[1] // K0
            real_code0_all = model.encoders[0](full_bytes[:, :(n_blocks_prev + 1) * K0], level=0,
                                                window=model.windows[0], compute_ntp=False)["code"]
            next_code0 = real_code0_all[:, n_blocks_prev:n_blocks_prev + 1, :]
            code_parts += [next_code0]
            code0 = torch.cat(code_parts, dim=1)
            code_embeds0 = bb0.quant.embed_for_decode(bb0, code0)
            n_blocks = n_blocks_prev + 1

            code1 = model.encoders[1](code0, level=1, window=model.windows[1], compute_ntp=False)["code"]
            code_embeds1 = bb1.quant.embed_for_decode(bb1, code1)
            code2 = model.encoders[2](code1, level=2, window=model.windows[2], compute_ntp=False)["code"]
            code_embeds2 = bb2.quant.embed_for_decode(bb2, code2)

            buf = torch.cat([all_bytes, all_bytes.new_zeros(all_bytes.shape[0], K0)], dim=1)
            for t in range(K0):
                x0 = bb0.embed_input(buf, True)
                pass1 = encode_like_self_attn_decode(bb0, x0, code_embeds0, K0, track0_window, track0_window)
                h_seed = seed_query_decode(bb0, pass1["saved_k"], pass1["saved_v"], code_embeds0, n_blocks, K0,
                                            track0_window, track0_window)
                h_real_b = pass1["hidden"].view(buf.shape[0], n_blocks, K0, D)
                h_query = h_seed[:, -1, :] if t == 0 else h_real_b[:, -1, t - 1, :]

                pos = n_blocks_prev * K0 + t
                h1 = upper_track_step(bb1, h_query.unsqueeze(1), pos, code_embeds1, cum_K1)
                h_final = upper_track_step(bb2, h1, pos, code_embeds2, cum_K2)
                next_byte = sample_next_byte(bb2.embed.weight, h_final[:, 0, :])
                buf = buf.clone()
                buf[:, pos] = next_byte
            all_bytes = buf

    generated = all_bytes[0, PROMPT_LEN:].tolist()
    ground_truth = full_bytes[0, PROMPT_LEN:].tolist()
    matches = sum(1 for a, b in zip(generated, ground_truth) if a == b)
    total = len(ground_truth)
    prefix = 0
    for a, b in zip(generated, ground_truth):
        if a != b:
            break
        prefix += 1
    print(f"[start={start}] byte match: {matches}/{total} = {matches/total*100:.2f}%  exact-prefix={prefix}")
    print_aligned_diff(generated, ground_truth)


def _display_char(b: int) -> str:
    """One byte -> exactly one display column, so generated/ground-truth/diff-marker lines
    stay vertically aligned (raw bytes() repr escapes some bytes as multi-char \\xNN, which
    breaks alignment and makes eyeballing the two strings against each other useless)."""
    if b == 10:
        return "¶"  # newline -> visible pilcrow, keeps line length fixed
    if b == 9:
        return "␉"  # tab -> visible symbol
    if 32 <= b < 127:
        return chr(b)
    return "·"  # any other control/non-ascii byte -> visible dot


def print_aligned_diff(generated: list, ground_truth: list, width: int = 80) -> None:
    gen_s = "".join(_display_char(b) for b in generated)
    gt_s = "".join(_display_char(b) for b in ground_truth)
    marker = "".join(" " if a == b else "^" for a, b in zip(generated, ground_truth))
    for i in range(0, max(len(gen_s), len(gt_s)), width):
        print(f"  gen: {gen_s[i:i + width]}")
        print(f"  gt:  {gt_s[i:i + width]}")
        print(f"       {marker[i:i + width]}")


for start in [0, 300, 600, 1200, 2000]:
    run(start)
