"""scripts/qual_gen_v4_2.py — simple qualitative generation for
qcute.qcute_refine_v4_2 models.

AR-generates continuations (via generate_no_cache -- generate_kv_cache
doesn't support this session's windowed attn_window[0] configs; both
route through the same RefineLM._encode training/eval itself uses, so
val_bpb never diverges from what generation actually does) for
randomly-picked prompts —
default 10 from the train region, 2 from val — printing generated bytes
next to ground truth. Also decodes level 0's own output CODE (what it
hands up to level 1) for both the ground-truth and the generated span,
via a simple nearest-class/BSQ-bit decode back into the byte alphabet —
not a claim it will be human-readable, just makes visible what this
session's own discussion speculated about (docs/hierarchical_fusion_designs.md
has no entry for this specifically; see the chat: "for v4 and v4.2...
each level basically a compressor to known length, can be readable
text, some concepts pooled to a single byte letter").

No --checkpoint given: auto-picks the checkpoint with the lowest
best_val_bpb among run logs matching --pattern (default
"qcute_refine_v4_2_k32_narrow_simplex*" — session: "choose simplex model,
was simple and good bpb"), by scanning logs/<run>/run.log for the last
"best_val_bpb=" occurrence.

    uv run python scripts/qual_gen_v4_2.py
    uv run python scripts/qual_gen_v4_2.py --pattern "qcute_refine_v4_2_k32_narrow*"
    uv run python scripts/qual_gen_v4_2.py --checkpoint checkpoints/qcute_refine_v4_2_k32_narrow_simplex_l2/best.pt
"""
from __future__ import annotations

import argparse
import re
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import torch
import torch.nn.functional as F

from qcute.qcute_refine_v4_2 import Config, RefineLM, generate_no_cache, load_enwik8, split_train_val, dqbits_to_byte


def find_best_checkpoint(logs_dir: Path, checkpoints_dir: Path, pattern: str) -> tuple[Path, str, float]:
    candidates = []
    for run_log in sorted(logs_dir.glob(f"{pattern}/run.log")):
        run_name = run_log.parent.name
        best_pt = checkpoints_dir / run_name / "best.pt"
        if not best_pt.exists():
            continue
        vals = re.findall(r"best_val_bpb=([0-9.]+)", run_log.read_text())
        if not vals:
            continue
        candidates.append((float(vals[-1]), run_name, best_pt))
    if not candidates:
        raise SystemExit(f"no checkpoints with best_val_bpb found under {logs_dir}/{pattern}/run.log")
    candidates.sort(key=lambda t: t[0])
    print(f"candidates matching {pattern!r} (lowest best_val_bpb first):")
    for bpb, name, _ in candidates:
        print(f"  {bpb:.4f}  {name}")
    bpb, name, path = candidates[0]
    print(f"-> chosen: {name} (best_val_bpb={bpb:.4f})\n")
    return path, name, bpb


def pick_offsets(region_len: int, n: int, prompt_len: int, gen_len: int, align: int, seed: int) -> list[int]:
    g = torch.Generator().manual_seed(seed)
    max_start = region_len - (prompt_len + gen_len)
    if max_start <= 0:
        raise SystemExit(f"region too short ({region_len} bytes) for prompt_len={prompt_len} + gen_len={gen_len}")
    offsets = (torch.rand(n, generator=g) * max_start).long()
    return sorted((o - o % align).item() for o in offsets)


def level0_code_ids(model: RefineLM, full_bytes: torch.Tensor, device: str) -> torch.Tensor:
    """What level 0 hands up to level 1 for this span -- i.e. level 1's OWN
    INPUT, not its output (see chat: _encode appends x_list[i] = seq_repr
    BEFORE running level i, so x_list[1] is level 0's c_i, computed
    deterministically from these given bytes -- never level 1's own
    prediction). quant_type="simplex": the code IS already a class index
    into the SAME vocab=256 table byte-level sampling uses (argmax, exact
    when code_bits==8). quant_type in ("bsq","identity"): dq-bit sign
    pattern, decoded via the SAME dqbits_to_byte byte-level sampling uses."""
    if model.n_levels < 2:
        return torch.zeros(0, dtype=torch.long)
    with torch.no_grad():
        *_, x_list = model._encode(full_bytes.unsqueeze(0).to(device), n_active=2, compute_ntp=False)
    c0 = x_list[1]   # level 0's own output code = level 1's own input, [1, n_blocks, ...]
    if model.cfg.quant_type == "simplex":
        return c0[0].argmax(-1)   # [n_blocks], exact byte id when code_bits==8 (this session's default)
    return dqbits_to_byte(c0[0])   # [n_blocks]


@torch.no_grad()
def generate_level1_codes(model: RefineLM, prompt_code_ids: torch.Tensor, n_new_codes: int, device: str) -> torch.Tensor:
    """AR-generates level 1's OWN continuation of the level-0-code stream --
    level 1 sampling ITSELF, autoregressively feeding its own predicted
    codes back in, the same shape as generate_no_cache but one level up
    (no KV cache, full recompute each step -- fine at this scale, same
    "obviously correct" tradeoff generate_no_cache itself makes). Level 1
    is always the TOP level in this session's 2-level configs, so no
    fuse_kv (nothing above it to read from) -- same "top active level
    keeps PASS 1" case _encode's own docstring describes.

    Only implemented for quant_type="simplex" (weight-tied vocab=256
    classifier, same F.linear(h, embed.weight).argmax(-1) pattern
    _sample_next_byte already uses for level 0 -- level 1 shares the exact
    same nn.Embedding object under this quant_type's default sharing)."""
    assert model.cfg.quant_type == "simplex", "generate_level1_codes only implemented for quant_type='simplex'"
    assert model.n_levels >= 2
    enc1 = model.encoders[1]
    V = enc1.embed.weight.size(0)
    ids = prompt_code_ids.to(device).long()
    if ids.dim() == 1:
        ids = ids.unsqueeze(0)
    x_in = F.one_hot(ids, V).float()
    for _ in range(n_new_codes):
        _, _, _, h = enc1(x_in, compute_ntp=False)
        next_id = F.linear(h[:, -1, :], enc1.embed.weight).argmax(-1)   # [B]
        x_in = torch.cat([x_in, F.one_hot(next_id, V).float().unsqueeze(1)], dim=1)
        ids = torch.cat([ids, next_id.unsqueeze(1)], dim=1)
    return ids[0]


def ids_to_bytes(ids: torch.Tensor) -> bytes:
    return bytes(ids.clamp(0, 255).tolist())


def b2s(b: bytes) -> str:
    return b.decode("latin-1").translate({9: " ", 10: "↵", 13: ""})


def main():
    p = argparse.ArgumentParser(description="Qualitative AR generation for a trained qcute_refine_v4_2 model")
    p.add_argument("--checkpoint", type=Path, default=None, help="explicit best.pt; default: auto-pick lowest best_val_bpb under --pattern")
    p.add_argument("--logs_dir", type=Path, default=Path("logs"))
    p.add_argument("--checkpoints_dir", type=Path, default=Path("checkpoints"))
    p.add_argument("--pattern", default="qcute_refine_v4_2_k32_narrow_simplex*")
    p.add_argument("--n_train", type=int, default=10)
    p.add_argument("--n_val", type=int, default=2)
    p.add_argument("--prompt_bytes", type=int, default=64)
    p.add_argument("--gen_bytes", type=int, default=64)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--data", type=Path, default=Path("datasets/enwik8_1M.gz"), help="not part of Config -- a train-script-only arg, matching every config file's own convention")
    p.add_argument("--val_frac", type=float, default=0.1)
    p.add_argument("--out_dir", type=Path, default=Path("logs/qual_gen_v4_2"))
    p.add_argument("--device", default=None, help="override auto device pick -- e.g. 'cpu' to avoid contending with a concurrent MPS training job")
    args = p.parse_args()

    device = args.device or ("mps" if torch.backends.mps.is_available() else ("cuda" if torch.cuda.is_available() else "cpu"))

    if args.checkpoint is not None:
        ckpt_path, run_name = args.checkpoint, args.checkpoint.parent.name
    else:
        ckpt_path, run_name, _ = find_best_checkpoint(args.logs_dir, args.checkpoints_dir, args.pattern)

    ckpt = torch.load(ckpt_path, map_location=device)
    cfg = Config(**ckpt["cfg"])
    model = RefineLM(cfg).to(device)
    model.load_state_dict(ckpt["model"])
    model.eval()
    print(f"loaded {ckpt_path} (step={ckpt.get('step')})  Ks={cfg.Ks} dq={cfg.dq} quant_type={cfg.quant_type} context_len={cfg.context_len}\n")

    data = load_enwik8(args.data)
    train_data, val_data = split_train_val(data, args.val_frac)

    align = cfg.Ks[0]
    if args.prompt_bytes % align or args.gen_bytes % align:
        raise SystemExit(f"--prompt_bytes/--gen_bytes must be multiples of Ks[0]={align}")

    samples = []
    for region_name, region, n in [("train", train_data, args.n_train), ("val", val_data, args.n_val)]:
        for off in pick_offsets(len(region), n, args.prompt_bytes, args.gen_bytes, align, args.seed):
            samples.append((region_name, off, region))

    args.out_dir.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y%m%d_%H%M%S")
    txt_path = args.out_dir / f"{run_name}_{stamp}.txt"
    lines = [f"model: {run_name}\ncheckpoint: {ckpt_path}\nKs={cfg.Ks} dq={cfg.dq} quant_type={cfg.quant_type}\n\n"]

    for region_name, off, region in samples:
        prompt = region[off: off + args.prompt_bytes]
        gt = region[off + args.prompt_bytes: off + args.prompt_bytes + args.gen_bytes]
        out = generate_no_cache(model, prompt, args.gen_bytes, device)   # [prompt_bytes + gen_bytes] -- not
                                                                          # generate_kv_cache: these configs use
                                                                          # windowed attn at level 0, unsupported there
        gen_cont = out[args.prompt_bytes:].cpu()

        code_ids_gt = level0_code_ids(model, torch.cat([prompt, gt]), device)
        code_ids_gen = level0_code_ids(model, out.cpu(), device)
        lvl1_gt = ids_to_bytes(code_ids_gt)
        lvl1_gen = ids_to_bytes(code_ids_gen)

        lvl1_ar_line = ""
        if cfg.quant_type == "simplex":
            n_prompt_codes = args.prompt_bytes // align
            n_new_codes = args.gen_bytes // align
            prompt_code_ids = level0_code_ids(model, prompt, device)   # level 1's own input for JUST the prompt span
            assert prompt_code_ids.numel() == n_prompt_codes
            lvl1_ar_ids = generate_level1_codes(model, prompt_code_ids, n_new_codes, device)
            lvl1_ar_gen = ids_to_bytes(lvl1_ar_ids[n_prompt_codes:].cpu())   # level 1's OWN predicted continuation,
                                                                              # never driven by ground-truth/generated
                                                                              # level-0 bytes -- level 1 sampling itself
            lvl1_ar_line = f"level1_ar_gen  : {b2s(lvl1_ar_gen)}   (level 1's OWN predicted next codes, not re-derived from bytes)\n"

        block = (
            f"=== {region_name} offset={off} ===\n"
            f"prompt      : {b2s(bytes(prompt.tolist()))}\n"
            f"gen (cont.) : {b2s(bytes(gen_cont.tolist()))}\n"
            f"gt  (cont.) : {b2s(bytes(gt.tolist()))}\n"
            f"level0code[gt] : {b2s(lvl1_gt)}   (each char ~= {align} raw bytes -- level 1's INPUT, not its output)\n"
            f"level0code[gen]: {b2s(lvl1_gen)}\n"
            f"{lvl1_ar_line}\n"
        )
        print(block, end="")
        lines.append(block)

    txt_path.write_text("".join(lines))
    print(f"wrote {txt_path}")


if __name__ == "__main__":
    main()
